package dev.exodus.wasteland.arena;

public enum ArenaPhase {
    DEPENDENCY_CHECK, CITY_SAMPLING, TEMPLATE_VALIDATION, PREGENERATION,
    POI_PLANNING, TERRAIN_PREPARATION, STRUCTURE_PLACEMENT, MARKER_PROCESSING, FINAL_VALIDATION, COMPLETE
}
