package dev.exodus.wasteland.arena;

public enum ArenaPhase {
    DEPENDENCY_CHECK, CITY_SAMPLING, TEMPLATE_VALIDATION, PREGENERATION,
    POI_PLANNING, POI_CHUNK_PREPARATION, TERRAIN_PREPARATION, STRUCTURE_PLACEMENT,
    MARKER_PROCESSING, POI_VERIFICATION, FINAL_VALIDATION, COMPLETE
}
