package dev.exodus.teleporter.menu;
import dev.exodus.*;import dev.exodus.teleporter.*;import dev.exodus.teleporter.blockentity.ExodusTeleporterBlockEntity;import dev.exodus.teleporter.domain.*;import dev.exodus.teleporter.item.*;import net.minecraft.core.BlockPos;import net.minecraft.network.FriendlyByteBuf;import net.minecraft.world.*;import net.minecraft.world.entity.player.*;import net.minecraft.world.inventory.*;import net.minecraft.world.item.ItemStack;
import java.util.UUID;
public final class ExodusTeleporterMenu extends AbstractContainerMenu {
 private final net.minecraft.world.inventory.ContainerData buttons=new net.minecraft.world.inventory.SimpleContainerData(3);private final Inventory inventory;
 private final Container device;private final ExodusTeleporterBlockEntity blockEntity;
 public static ExodusTeleporterMenu client(int id,Inventory inv,FriendlyByteBuf buf){BlockPos pos=buf.readBlockPos();var be=inv.player.level().getBlockEntity(pos);return new ExodusTeleporterMenu(id,inv,be instanceof ExodusTeleporterBlockEntity t?t:new SimpleContainer(9));}
 public ExodusTeleporterMenu(int id,Inventory inv,Container container){super(ExodusTeleporterRegistry.TELEPORTER_MENU.get(),id);inventory=inv;addDataSlots(buttons);device=container;blockEntity=container instanceof ExodusTeleporterBlockEntity t?t:null;checkContainerSize(container,9);container.startOpen(inv.player);
  for(int row=0;row<3;row++)for(int col=0;col<3;col++){int slot=row*3+col;addSlot(new Slot(container,slot,62+col*18,17+row*18){@Override public boolean mayPlace(ItemStack stack){if(!(stack.getItem() instanceof TeleporterComponentItem item))return false;if(inv.player.level().isClientSide)return TeleporterComponent.forSlot(slot)==item.component();UUID id=ExodusSavedData.get(inv.player.getServer()).matchId;return TeleporterInventoryPolicy.mayInsert(slot,item.component(),ComponentStacks.state(stack),id,blockEntity!=null&&blockEntity.locked());}@Override public boolean mayPickup(Player player){return blockEntity==null||!blockEntity.locked();}@Override public int getMaxStackSize(){return 1;}});}
  for(int row=0;row<3;row++)for(int col=0;col<9;col++)addSlot(new Slot(inv,col+row*9+9,8+col*18,84+row*18));for(int col=0;col<9;col++)addSlot(new Slot(inv,col,8+col*18,142));}
 @Override public boolean stillValid(Player player){return device.stillValid(player)&&(player.level().isClientSide||player instanceof net.minecraft.server.level.ServerPlayer sp&&MatchManager.isActiveMatchPlayer(sp));}
 @Override public void broadcastChanges(){if(blockEntity!=null&&inventory.player instanceof net.minecraft.server.level.ServerPlayer p){dev.exodus.device.DeviceIndex.observe(blockEntity);buttons.set(0,dev.exodus.device.DeviceOwnershipService.canClaim(p,blockEntity.getBlockPos())?1:0);buttons.set(1,dev.exodus.device.DeviceOwnershipService.canSetSpawn(p,blockEntity.getBlockPos())?1:0);buttons.set(2,blockEntity.locked()?1:0);}super.broadcastChanges();}
 @Override public boolean clickMenuButton(Player player,int id){if(!(player instanceof net.minecraft.server.level.ServerPlayer p)||blockEntity==null||!stillValid(player))return false;if(id==0){dev.exodus.device.DeviceOwnershipService.requestClaim(p,blockEntity.getBlockPos());return true;}if(id==1){dev.exodus.device.DeviceOwnershipService.setSpawn(p,blockEntity.getBlockPos());return true;}return false;}
 public boolean canClaim(){return buttons.get(0)==1;}public boolean canSetSpawn(){return buttons.get(1)==1;}public boolean activeDevice(){return buttons.get(2)==1;}
 public int installedCount(){int count=0;for(int i=0;i<9;i++)if(!getSlot(i).getItem().isEmpty())count++;return count;}
 @Override public ItemStack quickMoveStack(Player player,int index){return ItemStack.EMPTY;}@Override public void removed(Player player){super.removed(player);device.stopOpen(player);}
}
