package dev.exodus.teleporter;
import dev.exodus.*;import dev.exodus.teleporter.block.ExodusTeleporterBlock;import dev.exodus.teleporter.blockentity.ExodusTeleporterBlockEntity;import dev.exodus.teleporter.domain.*;import dev.exodus.teleporter.item.*;import net.minecraft.core.*;import net.minecraft.core.registries.Registries;import net.minecraft.network.chat.Component;import net.minecraft.resources.*;import net.minecraft.server.*;import net.minecraft.server.level.*;import net.minecraft.sounds.*;import net.minecraft.world.*;import net.minecraft.world.entity.item.ItemEntity;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.Level;import net.minecraft.world.BossEvent;import java.util.*;
public final class TeleporterService{
 private static final Map<MinecraftServer,ServerBossEvent> BARS=new WeakHashMap<>();private TeleporterService(){}
 public static void tryActivate(ServerLevel level,BlockPos pos,ExodusTeleporterBlockEntity be){ExodusSavedData d=ExodusSavedData.get(level.getServer());if(d.state!=MatchState.RUNNING||d.matchId==null||be.locked()||be.installed()!=9)return;if(d.teleporter.active()!=null)return;if(!d.teleporter.rareClaims().containsAll(List.of(TeleporterComponent.FACILITY_ALPHA_KEY,TeleporterComponent.FACILITY_BETA_KEY,TeleporterComponent.DIMENSIONAL_CORE)))return;int seconds=ExodusConfig.TELEPORTER_COUNTDOWN_SECONDS.get(),radius=ExodusConfig.TELEPORTER_VICTORY_RADIUS_MILLIBLOCKS.get(),capacity=ExodusConfig.TELEPORTER_CAPACITY.get();d.teleporter.active(new TeleporterSavedState.Active(d.matchId,level.dimension().location().toString(),pos.asLong(),level.getGameTime(),seconds,radius,capacity));d.setDirty();be.matchId(d.matchId);be.lock();level.setBlock(pos,level.getBlockState(pos).setValue(ExodusTeleporterBlock.ACTIVE,true),3);force(level,pos,radius,true);bar(level.getServer(),d.teleporter.active());}
 public static void tick(MinecraftServer server){ExodusSavedData d=ExodusSavedData.get(server);var active=d.teleporter.active();if(active==null)return;ServerLevel level=level(server,active.dimension());if(level==null)return;BlockPos pos=BlockPos.of(active.blockPos());CountdownSnapshot snapshot=new CountdownSnapshot(active.startTick(),active.durationSeconds(),active.radiusMilliblocks()/1000.0,active.capacity());ServerBossEvent bar=bar(server,active);long now=level.getGameTime(),remaining=snapshot.remainingTicks(now);bar.setProgress((float)snapshot.progress(now));bar.setName(Component.literal(String.format("Exodus Teleporter — X: %d Y: %d Z: %d — %02d:%02d",pos.getX(),pos.getY(),pos.getZ(),remaining/1200,(remaining/20)%60)));reconcileAudience(server,d,bar);if(now%20==0){level.sendParticles(net.minecraft.core.particles.ParticleTypes.PORTAL,pos.getX()+.5,pos.getY()+1,pos.getZ()+.5,remaining<=1200?24:8,.6,.7,.6,.1);level.playSound(null,pos,SoundEvents.PORTAL_AMBIENT,SoundSource.BLOCKS,.25f,1f);}if(snapshot.expired(now)){List<EscapeCandidate> candidates=new ArrayList<>();for(ServerPlayer p:level.players()){boolean eligible=MatchManager.isActiveMatchPlayer(p);candidates.add(new EscapeCandidate(p.getUUID(),p.distanceToSqr(pos.getX()+.5,pos.getY()+.5,pos.getZ()+.5),eligible));}List<UUID>winners=WinnerPolicy.select(candidates,snapshot.radius(),snapshot.capacity());MatchManager.endWithWinners(server,winners);}}
 private static ServerBossEvent bar(MinecraftServer server,TeleporterSavedState.Active active){return BARS.computeIfAbsent(server,s->new ServerBossEvent(Component.literal("Exodus Teleporter"),BossEvent.BossBarColor.PURPLE,BossEvent.BossBarOverlay.PROGRESS));}
 private static void reconcileAudience(MinecraftServer server,ExodusSavedData d,ServerBossEvent bar){bar.removeAllPlayers();for(var entry:d.associations.entrySet()){ServerPlayer p=server.getPlayerList().getPlayer(entry.getKey());if(BossBarAudiencePolicy.visible(entry.getValue(),p!=null))bar.addPlayer(p);}}
 public static void cleanup(MinecraftServer server,UUID matchId){ExodusSavedData d=ExodusSavedData.get(server);var active=d.teleporter.active();ServerBossEvent bar=BARS.remove(server);if(bar!=null)bar.removeAllPlayers();if(active!=null){ServerLevel level=level(server,active.dimension());if(level!=null){BlockPos pos=BlockPos.of(active.blockPos());force(level,pos,active.radiusMilliblocks(),false);if(level.getBlockEntity(pos) instanceof ExodusTeleporterBlockEntity be)be.reset();if(level.getBlockState(pos).hasProperty(ExodusTeleporterBlock.ACTIVE))level.setBlock(pos,level.getBlockState(pos).setValue(ExodusTeleporterBlock.ACTIVE,false),3);for(var entity:level.getAllEntities())if(entity instanceof ItemEntity item&&ComponentStacks.isCurrent(item.getItem(),matchId))item.discard();}}for(ServerPlayer p:server.getPlayerList().getPlayers()){remove(p.getInventory(),matchId);remove(p.getEnderChestInventory(),matchId);}d.teleporter.clearCurrent(matchId);d.setDirty();}
 private static void remove(Container c,UUID id){for(int i=0;i<c.getContainerSize();i++)if(ComponentStacks.isCurrent(c.getItem(i),id))c.setItem(i,ItemStack.EMPTY);}
 private static void force(ServerLevel level,BlockPos pos,int radiusMilli,boolean value){int radius=(int)Math.ceil(radiusMilli/1000.0);int minX=(pos.getX()-radius)>>4,maxX=(pos.getX()+radius)>>4,minZ=(pos.getZ()-radius)>>4,maxZ=(pos.getZ()+radius)>>4;for(int x=minX;x<=maxX;x++)for(int z=minZ;z<=maxZ;z++)level.setChunkForced(x,z,value);}
 private static ServerLevel level(MinecraftServer server,String id){return server.getLevel(ResourceKey.create(Registries.DIMENSION,new ResourceLocation(id)));}
}
