package dev.exodus.teleporter;
import dev.exodus.*;import dev.exodus.teleporter.block.ExodusTeleporterBlock;import dev.exodus.teleporter.blockentity.ExodusTeleporterBlockEntity;import dev.exodus.teleporter.domain.*;import dev.exodus.teleporter.item.*;import net.minecraft.core.*;import net.minecraft.core.registries.Registries;import net.minecraft.network.chat.Component;import net.minecraft.resources.*;import net.minecraft.server.*;import net.minecraft.server.level.*;import net.minecraft.sounds.*;import net.minecraft.world.*;import net.minecraft.world.entity.item.ItemEntity;import net.minecraft.world.item.ItemStack;import net.minecraft.world.level.Level;import net.minecraft.world.BossEvent;import java.util.*;
public final class TeleporterService{
 private TeleporterService(){}
 public static void tryActivate(ServerLevel level,BlockPos pos,ExodusTeleporterBlockEntity be){ExodusSavedData d=ExodusSavedData.get(level.getServer());if(d.state!=MatchState.RUNNING||d.matchId==null||be.locked()||be.installed()!=9)return;if(!level.dimension().location().toString().equals(d.dimension)||!d.matchId.equals(be.matchId()))return;if(d.teleporter.active()!=null)return;if(!d.teleporter.rareClaims().containsAll(List.of(TeleporterComponent.FACILITY_ALPHA_KEY,TeleporterComponent.FACILITY_BETA_KEY,TeleporterComponent.DIMENSIONAL_CORE)))return;int seconds=ExodusConfig.TELEPORTER_COUNTDOWN_SECONDS.get(),radius=ExodusConfig.TELEPORTER_VICTORY_RADIUS_MILLIBLOCKS.get(),capacity=ExodusConfig.TELEPORTER_CAPACITY.get();d.teleporter.active(new TeleporterSavedState.Active(d.matchId,level.dimension().location().toString(),pos.asLong(),level.getGameTime(),seconds,radius,capacity));d.setDirty();be.matchId(d.matchId);be.lock();level.setBlock(pos,level.getBlockState(pos).setValue(ExodusTeleporterBlock.ACTIVE,true),3);force(level,pos,radius,true);dev.exodus.device.DeviceIndex.observe(be);}
 public static void tick(MinecraftServer server){ExodusSavedData d=ExodusSavedData.get(server);var active=d.teleporter.active();if(active==null)return;ServerLevel level=level(server,active.dimension());if(level==null)return;BlockPos pos=BlockPos.of(active.blockPos());CountdownSnapshot snapshot=new CountdownSnapshot(active.startTick(),active.durationSeconds(),active.radiusMilliblocks()/1000.0,active.capacity());long now=level.getGameTime(),remaining=snapshot.remainingTicks(now);if(now%20==0){level.sendParticles(net.minecraft.core.particles.ParticleTypes.PORTAL,pos.getX()+.5,pos.getY()+1,pos.getZ()+.5,remaining<=1200?24:8,.6,.7,.6,.1);level.playSound(null,pos,SoundEvents.PORTAL_AMBIENT,SoundSource.BLOCKS,.25f,1f);}if(snapshot.expired(now)){List<EscapeCandidate> candidates=new ArrayList<>();for(ServerPlayer p:level.players()){boolean eligible=p.isAlive()&&MatchManager.isActiveMatchPlayer(p);candidates.add(new EscapeCandidate(p.getUUID(),p.distanceToSqr(pos.getX()+.5,pos.getY()+.5,pos.getZ()+.5),eligible));}List<UUID>winners=WinnerPolicy.select(candidates,snapshot.radius(),snapshot.capacity());MatchManager.endWithWinners(server,winners);}}
 public static void pause(MinecraftServer server,long ticks){if(ticks<=0)return;var d=ExodusSavedData.get(server);var a=d.teleporter.active();if(a!=null){d.teleporter.active(new TeleporterSavedState.Active(a.matchId(),a.dimension(),a.blockPos(),a.startTick()+ticks,a.durationSeconds(),a.radiusMilliblocks(),a.capacity()));d.setDirty();}}
 public static void resume(MinecraftServer server){var a=ExodusSavedData.get(server).teleporter.active();if(a==null)return;ServerLevel l=level(server,a.dimension());if(l!=null)force(l,BlockPos.of(a.blockPos()),a.radiusMilliblocks(),true);}
 public static void cleanup(MinecraftServer server,UUID matchId){ExodusSavedData d=ExodusSavedData.get(server);for(var device:d.session.devices.values()){ServerLevel stored=level(server,device.dimension());BlockPos at=BlockPos.of(device.position());if(stored!=null&&stored.hasChunkAt(at)&&stored.getBlockEntity(at) instanceof ExodusTeleporterBlockEntity partial)partial.reset();}var active=d.teleporter.active();if(active!=null){ServerLevel level=level(server,active.dimension());if(level!=null){BlockPos pos=BlockPos.of(active.blockPos());force(level,pos,active.radiusMilliblocks(),false);if(level.getBlockEntity(pos) instanceof ExodusTeleporterBlockEntity be)be.reset();if(level.getBlockState(pos).hasProperty(ExodusTeleporterBlock.ACTIVE))level.setBlock(pos,level.getBlockState(pos).setValue(ExodusTeleporterBlock.ACTIVE,false),3);for(var entity:level.getAllEntities())if(entity instanceof ItemEntity item&&ComponentStacks.isCurrent(item.getItem(),matchId))item.discard();}}for(ServerPlayer p:server.getPlayerList().getPlayers()){remove(p.getInventory(),matchId);remove(p.getEnderChestInventory(),matchId);}d.teleporter.clearCurrent(matchId);d.setDirty();}
 private static void remove(Container c,UUID id){for(int i=0;i<c.getContainerSize();i++)if(ComponentStacks.isCurrent(c.getItem(i),id))c.setItem(i,ItemStack.EMPTY);}
 private static void force(ServerLevel level,BlockPos pos,int radiusMilli,boolean value){int radius=(int)Math.ceil(radiusMilli/1000.0);int minX=(pos.getX()-radius)>>4,maxX=(pos.getX()+radius)>>4,minZ=(pos.getZ()-radius)>>4,maxZ=(pos.getZ()+radius)>>4;for(int x=minX;x<=maxX;x++)for(int z=minZ;z<=maxZ;z++)level.setChunkForced(x,z,value);}
 private static ServerLevel level(MinecraftServer server,String id){return server.getLevel(ResourceKey.create(Registries.DIMENSION,new ResourceLocation(id)));}
}
